### ISSUE TITLE
[preset-env] Add ability to error if polyfills are required

### ISSUE THREAD

**Issue by davidje13** [babel/babel-polyfills#10] opened 2020-04-04 22:32 UTC
## Feature Request

Some corejs polyfills are overly bloated (or have trivial alternatives in many situations) and it can be desirable to avoid the need for them. `preset-env` already has the ability to detect where polyfills would be required in code via `useBuiltIns` (and with more accuracy than a linter since it is the tool which actually adds the polyfill!)

Extending the existing concept of the `exclude` section to provide a way of forbidding individual polyfills would be useful for managing this:

```json5
{
  "useBuiltIns": "inline",
  "corejs": 3,
  "polyfills": {
    "web.url": "useBuiltIn", // or true
    "es.string.replace": "exclude",
    "web.immediate": "error"
  }
}
```

This would replace `exclude` (with a simple migration path) and has the advantage of having a less ambiguous name.

Unconfigured polyfills could default to either `useBuiltIn` (to match current behaviour and make it easier to adopt new polyfills) or `error` (to force developers to consider each newly required polyfill rather than blindly accepting it). I could see arguments for both defaults; not sure what's best (though I personally would prefer an `error` default).

**Comment by ljharb** [comment] 2020-05-02 20:48
I'm somewhat skeptical here; it's pretty impossible imo to confidently claim that nothing in your entire dependency graph cares about the edge cases, or exact spec compliance; I've seen that assumption bite far too many people in production.

**Comment by nicolo-ribaudo** [comment] 2020-05-02 21:07
I think this could be useful in two cases:
- `error` is useful if you know that the polyfill for X is slow/big and you want to be sure not to write any code that would need it
- if you are only polyfilling your own code (using `usage-global` or `usage-pure`, and not transpiling `node_modules`), then you can be confident that you don't need some edge cases to be handled.

However, I think that this (or at least, `error`) could be implemented by adding a lower-level function option that is called whenever a polyfill is injected. This also satisfies other use cases that have been requested in various channels:
- programmatically get a list of all the injected polyfills
- automatically `npm install` new polyfills (<-- This is something I personally don't like)

**Comment by WebReflection** [comment] 2020-05-02 23:07
Some polyfill is unreliable by specs, so I don’t see any guarantee one polyfill would grant any edge caae better than others, when specs don’t allow it (I.e. weak maps)

**Comment by ljharb** [comment] 2020-05-03 15:03
tbh I wouldn’t suggest including anything automatically that can’t be shimmed, like weak maps.

**Comment by pleunv** [comment] 2020-05-03 15:38
> 
> 
> I'm somewhat skeptical here; it's pretty impossible imo to confidently claim that nothing in your entire dependency graph cares about the edge cases, or exact spec compliance; I've seen that assumption bite far too many people in production.

I gues it's a trade-off you have to make. If you do want more and/or finegrained control over your polyfills you'll have to be aware of possible consequences. If you transpile `node_modules` (which we do as well - and everyone should) I definitely think you should be aware of the code in your deps and polyfills it's pulling in.
I also suspect (but haven't confirmed) that when a dependency does feature detection with a slow path fallback or provides an inline poly/ponyfill themselves it still includes a polyfill on babel's side. Cases like that you really want to avoid.

Another example I noticed is i.e. the recent addition of `Promise.prototype.finally`, which is now triggering the inclusion of a Promise polyfill up to Firefox v57. We don't use `finally()` and when we do it will be a very conscious decision, and I'm pretty sure none of our dependencies do either, but I do want to include a normal `Promise` polyfill (with our without `finally()`, doesn't matter) for IE/Edge. The only way to do this today is by excluding es.promise from babel and manually polyfilling it in your entry file.

While typing this and looking at the core-js code I'm noticing that excluding es.promise.finally might work as well, but I'll have to investigate. The problem is that many of these optimizations you might be able to do are not very straightforward to figure out today.

I do think that the out-of-the-box experience needs to remain the way it is now, but it definitely doesn't hurt providing more insight and possibly control over what's going on. I also feel people need to be educated better about the consequences of i.e. just dropping `preset-env` and a `browserslist` in your project and the effects it has on your payload size. Providing module/nomodule builds already offers a small improvement but definitely not to the extent some people would like to have you believe, and it also doesn't solve today's problem of sending way too large bundles over the wire.

**Comment by ljharb** [comment] 2020-05-03 16:30
Personally, i think transpiling code you didn’t author is never safe, and nobody should ever transpile node_modules :-)

**Comment by pleunv** [comment] 2020-05-03 16:34
Now _that_ has bitten us more than once in the past 😄 . Every library author has their own definitions of sets of browsers that they should support, and some started to only provide ES6 builds. Selective transpilation might be a better approach, but there definitely needs to be some sort of escape hatch in case the provided output doesn't meet your use-case.

**Comment by jrylan** [comment] 2020-05-04 00:42
> Personally, i think transpiling code you didn’t author is never safe, and nobody should ever transpile node_modules :-)

@ljharb In a perfect world, that would be great. But even `create-react-app` processes node_modules: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/webpack.config.js#L450.

In my experience, there are plenty of packages out there that aren't shipped transpiled down to ES5, so if you want to use them, you have to at least selectively process node_modules.

**Comment by ljharb** [comment] 2020-05-04 05:11
@jrylan yes, and CRA's decision was, and remains, a very bad one - they did it because people kept asking for it, not because it was a good idea.

You shouldn't use those packages; there's always alternatives with the proper support.

**Comment by pleunv** [comment] 2020-05-04 07:42
I'm unaware about the reasoning behind not transpiling node_modules, could you clarify? 
How would you then deal with a moving browser target? And legacy support? Can't keep forcing authors to transpile down to ES5 forever.

Everybody has different target requirements, and now that module/nomodule bundles are starting to pop up it gets even harder to optimize. To me the ideal world looks like one where libraries provide an additional esm output that contains ES6 that's only been transpiled down to eliminate any proposals that i.e. preset-env can't deal with out of the box. Everything else is left up to the consumer to transpile down to their targets.

**Comment by ljharb** [comment] 2020-05-04 07:49
@pleunv yes, you can :-) there's no safe solution yet; transpiling node_modules doesn't do it.

Specifically, it's that most transforms are not actually 1:1, which means there's caveats, and only the author of the code can say for sure if those caveats matter or not.

**Comment by jrylan** [comment] 2020-05-04 14:26
@ljharb Can you elaborate on your recommended approach if you suggest to not transpile node_modules?

Obviously it's unrealistic to ask all module authors to transpile everything down to ES5, and there are several cavets with that:

1. Transpiled code could include shims inline, bloating it's file size, when the consuming developer intends to use shim modules to reduce bundle size and avoid duplicating inline shims.

2. If a package author shipped with shims inline, what happens if there is a hard-to-discover edge-case bug in a particular version of the shim at the point they transpiled their code? There would be no easy way at all to fix that until the package author published a new version. 
Considering that we should be grateful that many authors publish their work for free in the first place; we can't expect every package author to be in the position to near-immediately publish an update to their packages the moment a bug is fixed in one of their dependencies.

I understand your point of view that only the original author could insure a transpiled version of their code was accurate, however is it not up to the consumer of their code to also test their integration in each environment? After all, source code is a static document and code itself describes it's intent.

Personally, when integrating package dependencies, I prefer to import the source ESM/ES6 (and even TypeScript) files whenever possible and transpile. I have been achieving smaller bundle sizes that way and have yet to hit a problem in an app that has full test coverage.

In fact, I've actually had MORE problems consuming code that was already transpiled. I've seen partially transpiled ES6 code where shims where injected BEFORE import statements... which works fine in Webpack, but rightfully fails when using native modules in Node.js v13+. I had to actually write a Babel plugin to correctly hoist import declarations to fix that one.

**Comment by davidje13** [comment] 2020-05-04 17:37
This thread seems to be focussing on transpilation of node_modules, but to clarify, when I originally raised this suggestion, it was on a project which does not transpile node_modules and uses `inline` mode (so any added polyfills wouldn't affect node_modules anyway).

There already exists a feature (`exclude`) which silently omits polyfills. This request is simply to allow noisily omitting them, which should make potential issues more visible.

**Comment by ljharb** [comment] 2020-05-04 18:15
@jrylan find me on any chat medium and I'm happy to discuss it further; I find it perfectly reasonable to ask all module authors to transpile everything down to ES5. Correctness and "works" matters more than bundle size.

**Comment by nicolo-ribaudo** [comment] 2020-05-04 18:19
@jrylan If "any chat medium" is too vague you can contact him on our Slack (https://github.com/babel/babel-polyfills/issues/10#issuecomment-609097875).

I'm now marking these comments as off-topic to keep the discussion focused on the original issue.

**Closed** 2020-05-21 22:25 UTC
Labels: enhancement
