### ISSUE TITLE
Error: Can't resolve '@babel/runtime-corejs3/helpers/asyncToGenerator'

### ISSUE THREAD

**Issue by nyngwang** [babel/babel-polyfills#202] opened 2024-01-26 06:24 UTC
I got the following error:

```
Error: Can't resolve '@babel/runtime-corejs3/helpers/asyncToGenerator'
```

In short, I have a js file that defines a `async` function, and I only install `@babel/runtime` not `@babel/runtime-corejs3` because I want to transpile those helpers myself instead of using those `pure` version ones provided in `@babel/runtime-corejs3`. But from the error above it seems that `babel-plugin-polyfill-corejs3` is still insisting on referencing things in `@babel/runtime-corejs3`. How to fix it?

**myfiles**

```js
export const myAsync = async () => {
}
```

**babel.config.js**

```js
export default {
  plugins: [
    '@babel/plugin-transform-runtime',
    [
      'polyfill-corejs3', {
        method: 'usage-global',
        // version: jsonPackage.dependencies['core-js'],
        // proposals: true,
      },
    ],
  ],
  presets: [
    '@babel/preset-env',
  ],
}
```

**package.json**

```
  "devDependencies": {
    "@babel/core": "^7.23.7",
    "@babel/plugin-transform-runtime": "^7.23.7",
    "@babel/preset-env": "^7.23.9",
    "@babel/preset-react": "^7.23.3",
    "babel-loader": "^9.1.3",
    "html-webpack-plugin": "^5.6.0",
    "webpack": "^5.89.0",
    "webpack-cli": "^5.1.4",
    "webpack-dev-server": "^4.15.1"
  },
  "dependencies": {
    "@babel/runtime": "^7.23.8",
    "core-js": "^3.35.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }
```

**Comment by nyngwang** [comment] 2024-01-26 11:48
Oh, after many hours of testing, I can confirm that this is a serious bug. If I change back to `@babel/preset-env` `useBuiltIns: 'usage'`+`@babel/runtime` then there will be no usage of `@babel/runtime-corejs3` in the output bundle.

The current behaviour of `@babel/preset-env`+`polyfill-corejs3` `method: 'usage-global'`+`@babel/runtime` is NOT the same as the old way `@babel/preset-env` `useBuiltIns: 'usage` + `@babel/runtime`. It's worse than that if there is no solution for this issue: it failed to compile a simple `async` function without depending on `@babel/runtime-corejs3`. But wait I have specified the method as usage-**global**... so why would that @babel/runtime-**corejs3** appear here?

**Comment by nicolo-ribaudo** [comment] 2024-01-26 18:57
Closing as duplicate of https://github.com/babel/babel/issues/16238

**Closed** 2024-01-26 18:57 UTC
